// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTml8goDbcCXoHWGrKQhjoV0nCQwwDfAM',
    appId: '1:761202198915:web:39eb694d082c180e360eb6',
    messagingSenderId: '761202198915',
    projectId: 'moodlog-3d7de',
    authDomain: 'moodlog-3d7de.firebaseapp.com',
    storageBucket: 'moodlog-3d7de.firebasestorage.app',
    measurementId: 'G-WE7WFSZ8D0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6pTxRUbbmDCz5dQpk112_XCXuI7_8AfU',
    appId: '1:761202198915:android:f07a4ede6cc6f8ec360eb6',
    messagingSenderId: '761202198915',
    projectId: 'moodlog-3d7de',
    storageBucket: 'moodlog-3d7de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKfLI127N5CCObMFnO4U593RkgFa5b-z4',
    appId: '1:761202198915:ios:04092dc55dac7baf360eb6',
    messagingSenderId: '761202198915',
    projectId: 'moodlog-3d7de',
    storageBucket: 'moodlog-3d7de.firebasestorage.app',
    iosBundleId: 'com.example.moodlog0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKfLI127N5CCObMFnO4U593RkgFa5b-z4',
    appId: '1:761202198915:ios:04092dc55dac7baf360eb6',
    messagingSenderId: '761202198915',
    projectId: 'moodlog-3d7de',
    storageBucket: 'moodlog-3d7de.firebasestorage.app',
    iosBundleId: 'com.example.moodlog0',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTml8goDbcCXoHWGrKQhjoV0nCQwwDfAM',
    appId: '1:761202198915:web:208f891e0123a287360eb6',
    messagingSenderId: '761202198915',
    projectId: 'moodlog-3d7de',
    authDomain: 'moodlog-3d7de.firebaseapp.com',
    storageBucket: 'moodlog-3d7de.firebasestorage.app',
    measurementId: 'G-HCPDPNNJ7B',
  );
}
